[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."scrape.mjs"]
  schedule = "0 2 * * *"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Access-Control-Allow-Origin = "*"
